M48
; DRILL file {KiCad 7.0.10} date Wed Jan 24 17:50:34 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-24T17:50:34-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.2974Y-3.7362
X5.2974Y-3.9638
T2
X3.6Y-2.025
X3.6Y-5.075
X5.4Y-2.025
X5.4Y-5.075
M30
