M48
; DRILL file {KiCad 7.0.10} date Mon Feb 12 03:45:48 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-12T03:45:48-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0280
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.4102Y-3.6725
X5.4102Y-3.9875
T2
X3.6Y-2.025
X3.6Y-5.075
X5.4Y-2.025
X5.4Y-5.075
M30
